### ISSUE TITLE
sorting

### ISSUE THREAD

**Issue by Maxnflaxl** [BeamMW/asset-minter-app#1]
**Bug title**
Sorting

**Bug description**
By default it opens the DApp with "Minted by" selected, but it should select "Id" by default and sort from the lowest to highest AID

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Beam Asset Minter DApp

**Current behaviour**
![grafik](https://github.com/BeamMW/asset-minter-app/assets/63856008/bcf6da94-08d7-45be-be6a-ab68e4cd682a)

**Expected behaviour**
sort by AID starting at the lowest and not by 'Minted by' ( Asset Minter ) 
![grafik](https://github.com/BeamMW/asset-minter-app/assets/63856008/034fa2de-3ac5-4723-a0c5-781b424fb96d)

**Additional Information**
RE https://t.me/beamdevsupport/11619

**Comment by jdraiv** [comment]
Hello! I will be handling this issue

**Comment by Maxnflaxl** [comment]
Great, thank you!
