### ISSUE TITLE
BAM: Bug in the displayed registration command

### ISSUE THREAD

**Issue by dbadol** [BeamMW/asset-minter-app#2]
**Bug description**
It seems that there is a bug in the registration command that is displayed at the top of the DApp front end: the OPT_LOGO_URL appears as a number, although it was entered as an URL (see screenshot).

**Platform and build**
* Seen on Windows 10 (not tested elsewhere)
* BEAM Build number: 7.5.13840

**Remark**
I am not opening another issue for it, but this registration command should be displayed in monospace! Also, a 'copy' button to copy the command to the clipboard would be handy (same button used for the addresses, by instance).

**Screenshot**
![image](https://github.com/BeamMW/asset-minter-app/assets/13353088/3c7c7fec-fd0f-410e-a6bc-276acf772f74)

**Comment by jdraiv** [comment]
Thank you for the detailed explanation, I will be tackling this issue.

**Comment by Maxnflaxl** [comment]
Great, thank you!
